name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Build Docker image
    - name: Build Docker image
      run: docker build -t stock-risk-analyzer-app .

    # Step 4: Run tests inside Docker
    - name: Run tests
      run: |
        docker run --rm stock-risk-analyzer-app /bin/bash -c "
          python3 -m venv venv && \
          source venv/bin/activate && \
          pip install -r requirements.txt && \
          pip install pytest && \
          pytest
        "

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy locally (example)
      run: |
        docker-compose down || true
        docker-compose up -d --build
