name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # ✅ Step 3: Linting (Code Quality Check)
    - name: Lint Python code
      run:
        pip install coverage pytest black flake8 isort mypy
        coverage run -m pytest
        coverage xml 
        black --check .
        flake8 .
        isort --check-only .
        mypy .

    # Step 4: Build Docker container
    - name: Build Docker image
      run: docker build -t stock-risk-analyzer .

    # Step 5: Run Tests
    - name: Run tests
      run: |
        docker run --rm stock-risk-analyzer pytest

    # Step 6: Deploy (optional)
    - name: Deploy
      run: |
        docker compose down || true
        docker compose up -d --build
